---
title: "boulder_longmont"
output: pdf_document
date: "2025-06-25"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(sf)
library(dplyr)
library(ggplot2)
library(spam)
library(fields)

setwd("~/Desktop/MINES/COGCC-Risk-Analysis/IC_Scripts/2024-2025/sp_point_data")
source("ZlogisticSmoother.R")       
source("ZLambdaGridSearch.R")
```

```{r}
usable_sf <- st_read("usable_point_data.geojson")

df <- usable_sf %>%
  st_drop_geometry() %>%
  select(-unique_id) %>%
  mutate(
    lon = as.numeric(sub("^\\((.*),.*$", "\\1", coords)),
    lat = as.numeric(sub("^.*,\\s*(.*)\\)$",  "\\1", coords))
  ) %>%
  filter(
    lon >= -105.85,
    lon <=  -104.79 + 0.2,  
    lat >=  39.42,
    lat <=  40.68
  )

model_data <- df %>%
  select(lon, lat, risk)

model_data %>% count(risk) %>% mutate(prop = n/sum(n))

ggplot(model_data, aes(x = lon, y = lat, color = factor(risk))) +
  geom_point(size = 1.7, alpha = 0.8) +
  scale_color_manual(
    name   = "Risk (0/1)",
    values = c("0" = "skyblue", "1" = "firebrick")
  ) +
  coord_fixed() +
  theme_minimal() +
  labs(
    title = "Zoomed to Boulder–Greeley",
    x     = "Longitude",
    y     = "Latitude"
  )
```


```{r}
to.factor <- c("status","flowline_action","location_type","fluid","material")
df <- df %>% mutate(across(all_of(to.factor), as.factor))

X <- model.matrix(
  ~ status + flowline_action + location_type + fluid + material +
    diameter_in + length_ft + line_age_yr,
  data = df
)[, -1]

Z <- X[, c(
  "statusNew_Construction",
  "flowline_actionRealignment",
  "flowline_actionRegistration",
  "location_typeWell_Site",
  "fluidMultiphase",
  "fluidOther",
  "materialSteel",
  "diameter_in",
  "length_ft",
  "line_age_yr"
)]

risk_model   <- df$risk
coord_model  <- as.matrix(df[, c("lon","lat")])

Z_df <- as.data.frame(Z)
Z_df$risk <- df$risk      

glm_sel <- glm(risk ~ . -1, data = Z_df, family = binomial(link = "logit"))
betaHat <- coef(glm_sel)
```

```{r}
profile <- LambdaGridSearch(
  coord_model,
  risk_model,
  Z = Z,
  betaHat = betaHat
)

bestLambda <- profile$bestLambda

MLEFit <- logisticSmoother(
  coord_model,
  risk_model,
  lambda = bestLambda,
  Z = Z,
  betaHat = betaHat
)
```



```{r}
dim(Z)
length(betaHat)
```















